# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/etudiant/Snake3D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/etudiant/Snake3D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etudiant/Snake3D/CMakeFiles /home/etudiant/Snake3D//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etudiant/Snake3D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Snake3D

# Build rule for target.
Snake3D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Snake3D
.PHONY : Snake3D

# fast build rule for target.
Snake3D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/build
.PHONY : Snake3D/fast

src/CubeRenderer.o: src/CubeRenderer.cpp.o
.PHONY : src/CubeRenderer.o

# target to build an object file
src/CubeRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/CubeRenderer.cpp.o
.PHONY : src/CubeRenderer.cpp.o

src/CubeRenderer.i: src/CubeRenderer.cpp.i
.PHONY : src/CubeRenderer.i

# target to preprocess a source file
src/CubeRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/CubeRenderer.cpp.i
.PHONY : src/CubeRenderer.cpp.i

src/CubeRenderer.s: src/CubeRenderer.cpp.s
.PHONY : src/CubeRenderer.s

# target to generate assembly for a file
src/CubeRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/CubeRenderer.cpp.s
.PHONY : src/CubeRenderer.cpp.s

src/control/CommandRegistry.o: src/control/CommandRegistry.cpp.o
.PHONY : src/control/CommandRegistry.o

# target to build an object file
src/control/CommandRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/CommandRegistry.cpp.o
.PHONY : src/control/CommandRegistry.cpp.o

src/control/CommandRegistry.i: src/control/CommandRegistry.cpp.i
.PHONY : src/control/CommandRegistry.i

# target to preprocess a source file
src/control/CommandRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/CommandRegistry.cpp.i
.PHONY : src/control/CommandRegistry.cpp.i

src/control/CommandRegistry.s: src/control/CommandRegistry.cpp.s
.PHONY : src/control/CommandRegistry.s

# target to generate assembly for a file
src/control/CommandRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/CommandRegistry.cpp.s
.PHONY : src/control/CommandRegistry.cpp.s

src/control/GameControls.o: src/control/GameControls.cpp.o
.PHONY : src/control/GameControls.o

# target to build an object file
src/control/GameControls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/GameControls.cpp.o
.PHONY : src/control/GameControls.cpp.o

src/control/GameControls.i: src/control/GameControls.cpp.i
.PHONY : src/control/GameControls.i

# target to preprocess a source file
src/control/GameControls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/GameControls.cpp.i
.PHONY : src/control/GameControls.cpp.i

src/control/GameControls.s: src/control/GameControls.cpp.s
.PHONY : src/control/GameControls.s

# target to generate assembly for a file
src/control/GameControls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/GameControls.cpp.s
.PHONY : src/control/GameControls.cpp.s

src/control/InputHandler.o: src/control/InputHandler.cpp.o
.PHONY : src/control/InputHandler.o

# target to build an object file
src/control/InputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/InputHandler.cpp.o
.PHONY : src/control/InputHandler.cpp.o

src/control/InputHandler.i: src/control/InputHandler.cpp.i
.PHONY : src/control/InputHandler.i

# target to preprocess a source file
src/control/InputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/InputHandler.cpp.i
.PHONY : src/control/InputHandler.cpp.i

src/control/InputHandler.s: src/control/InputHandler.cpp.s
.PHONY : src/control/InputHandler.s

# target to generate assembly for a file
src/control/InputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/control/InputHandler.cpp.s
.PHONY : src/control/InputHandler.cpp.s

src/keycontrole.o: src/keycontrole.cpp.o
.PHONY : src/keycontrole.o

# target to build an object file
src/keycontrole.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/keycontrole.cpp.o
.PHONY : src/keycontrole.cpp.o

src/keycontrole.i: src/keycontrole.cpp.i
.PHONY : src/keycontrole.i

# target to preprocess a source file
src/keycontrole.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/keycontrole.cpp.i
.PHONY : src/keycontrole.cpp.i

src/keycontrole.s: src/keycontrole.cpp.s
.PHONY : src/keycontrole.s

# target to generate assembly for a file
src/keycontrole.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/keycontrole.cpp.s
.PHONY : src/keycontrole.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/matrix/RotationMatrixX.o: src/matrix/RotationMatrixX.cpp.o
.PHONY : src/matrix/RotationMatrixX.o

# target to build an object file
src/matrix/RotationMatrixX.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/matrix/RotationMatrixX.cpp.o
.PHONY : src/matrix/RotationMatrixX.cpp.o

src/matrix/RotationMatrixX.i: src/matrix/RotationMatrixX.cpp.i
.PHONY : src/matrix/RotationMatrixX.i

# target to preprocess a source file
src/matrix/RotationMatrixX.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/matrix/RotationMatrixX.cpp.i
.PHONY : src/matrix/RotationMatrixX.cpp.i

src/matrix/RotationMatrixX.s: src/matrix/RotationMatrixX.cpp.s
.PHONY : src/matrix/RotationMatrixX.s

# target to generate assembly for a file
src/matrix/RotationMatrixX.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/matrix/RotationMatrixX.cpp.s
.PHONY : src/matrix/RotationMatrixX.cpp.s

src/matrix/RotationMatrixY.o: src/matrix/RotationMatrixY.cpp.o
.PHONY : src/matrix/RotationMatrixY.o

# target to build an object file
src/matrix/RotationMatrixY.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/matrix/RotationMatrixY.cpp.o
.PHONY : src/matrix/RotationMatrixY.cpp.o

src/matrix/RotationMatrixY.i: src/matrix/RotationMatrixY.cpp.i
.PHONY : src/matrix/RotationMatrixY.i

# target to preprocess a source file
src/matrix/RotationMatrixY.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/matrix/RotationMatrixY.cpp.i
.PHONY : src/matrix/RotationMatrixY.cpp.i

src/matrix/RotationMatrixY.s: src/matrix/RotationMatrixY.cpp.s
.PHONY : src/matrix/RotationMatrixY.s

# target to generate assembly for a file
src/matrix/RotationMatrixY.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Snake3D.dir/build.make CMakeFiles/Snake3D.dir/src/matrix/RotationMatrixY.cpp.s
.PHONY : src/matrix/RotationMatrixY.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Snake3D"
	@echo "... src/CubeRenderer.o"
	@echo "... src/CubeRenderer.i"
	@echo "... src/CubeRenderer.s"
	@echo "... src/control/CommandRegistry.o"
	@echo "... src/control/CommandRegistry.i"
	@echo "... src/control/CommandRegistry.s"
	@echo "... src/control/GameControls.o"
	@echo "... src/control/GameControls.i"
	@echo "... src/control/GameControls.s"
	@echo "... src/control/InputHandler.o"
	@echo "... src/control/InputHandler.i"
	@echo "... src/control/InputHandler.s"
	@echo "... src/keycontrole.o"
	@echo "... src/keycontrole.i"
	@echo "... src/keycontrole.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix/RotationMatrixX.o"
	@echo "... src/matrix/RotationMatrixX.i"
	@echo "... src/matrix/RotationMatrixX.s"
	@echo "... src/matrix/RotationMatrixY.o"
	@echo "... src/matrix/RotationMatrixY.i"
	@echo "... src/matrix/RotationMatrixY.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

